//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankaEntities : DbContext
    {
        public BankaEntities()
            : base("name=BankaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilanca> Bilancas { get; set; }
        public virtual DbSet<Imovina> Imovinas { get; set; }
        public virtual DbSet<Izvor_imovine> Izvor_imovine { get; set; }
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Kredit_> Kredit_ { get; set; }
        public virtual DbSet<Otplatna_tablica> Otplatna_tablica { get; set; }
        public virtual DbSet<Račun> Račun { get; set; }
        public virtual DbSet<Stednja> Stednjas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip_zaposlenika> Tip_zaposlenika { get; set; }
        public virtual DbSet<VrstaRačuna> VrstaRačuna { get; set; }
        public virtual DbSet<VrstaStednje> VrstaStednjes { get; set; }
        public virtual DbSet<Zaposlenik> Zaposleniks { get; set; }
    }
}
