//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredit_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kredit_()
        {
            this.Otplatna_tablica = new HashSet<Otplatna_tablica>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DatumPocetka { get; set; }
        public double Glavnica { get; set; }
        public int RokOtplate { get; set; }
        public Nullable<int> Zaposlenik_id { get; set; }
        public Nullable<int> Klijent_id { get; set; }
        public double KamatnaStopa { get; set; }
        public string NazivKredita { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otplatna_tablica> Otplatna_tablica { get; set; }
    }
}
