//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otplatna_tablica
    {
        public int Id { get; set; }
        public double Kamate { get; set; }
        public double Anuitet { get; set; }
        public double OtplatnaKvota { get; set; }
        public double OstatakDuga { get; set; }
        public double OtplaceniDio { get; set; }
        public Nullable<int> Kredit_id { get; set; }
        public int BrojMjeseca { get; set; }
    
        public virtual Kredit_ Kredit_ { get; set; }
        /// <summary>
        /// Konstruktor klase Otplatne tablice
        /// </summary>
        /// <param name="_id"></param>
        /// <param name="_kamate"></param>
        /// <param name="_anuitet"></param>
        /// <param name="_otplatnaKvota"></param>
        /// <param name="_ostatakDuga"></param>
        /// <param name="_otplaceniDio"></param>
        /// <param name="_brojMjeseca"></param>
        public Otplatna_tablica(int _id, double _kamate, double _anuitet, double _otplatnaKvota, double _ostatakDuga, double _otplaceniDio, int _brojMjeseca)
        {
            Id = _id;
            Kamate = _kamate;
            Anuitet = _anuitet;
            OtplatnaKvota = _otplatnaKvota;
            OstatakDuga = _ostatakDuga;
            OtplaceniDio = _otplaceniDio;
            BrojMjeseca = _brojMjeseca;

        }
    }
}
