//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Račun
    {
        public int Id { get; set; }
        public string IBAN { get; set; }
        public string BrojKartice { get; set; }
        public double Stanje { get; set; }
        public Nullable<double> DozvoljeniMinus { get; set; }
        public Nullable<int> Blokiran { get; set; }
        public Nullable<int> Klijent_id { get; set; }
        public Nullable<int> Vrsta_id { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        public virtual VrstaRačuna VrstaRačuna { get; set; }
    }
}
